name: Build

on:
  # 推送到 main 分支时触发
  push:
    branches: 
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # 也可以添加手动触发选项
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            build_command: build:mac
            artifact_name: "HSMod-Mac-*-Installer.dmg"
          - os: windows-latest
            build_command: build:win
            artifact_name: "HSMod-Windows-*-Setup.exe"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Package Version
        id: package-version
        shell: bash
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run ${{ matrix.build_command }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Release Directory
        shell: bash
        run: |
          ls -R release/

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/${{ steps.package-version.outputs.version }}/${{ matrix.artifact_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact for Debug
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix.os }}
          path: release/${{ steps.package-version.outputs.version }}
          retention-days: 5