name: Build

on:
  push:
    tags:
      - '*'  # 每次推送标签时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Get Package Version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build  # 请确保你有一个 build 脚本来打包应用

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          name: "Release v${{ env.version }}"
          body: |
            Changes in this Release:
            - First release for testing
          draft: true
          prerelease: false
          files: release/${{ env.version }}/HSMod-Mac-${{ env.version }}-Installer.dmg  # 请确保这路径和你的构建产物一致
