name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: "HSMod-Mac-*.dmg"
          - os: windows-latest
            artifact_name: "HSMod-Windows-*.exe"
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          files: |
            release/**/${{ matrix.artifact_name }} 