name: Build

on:
  push:
    tags:
      - '*'  # 每次推送标签时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 检出代码

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # 设置 Node.js 版本

      - name: Install Dependencies
        run: npm install  # 安装依赖

      - name: Build Application
        run: npm run build:all  # 执行 build 脚本

      - name: List Release Directory
        run: ls -R release/  # 列出构建目录，确认产物生成

      - name: Create Release
        uses: softprops/action-gh-release@v1  # 上传构建产物到 GitHub Releases
        with:
          tag_name: v${{ env.version }}
          name: "Release v${{ env.version }}"
          files: release/${{ env.version }}/HSMod-Mac-${{ env.version }}-Installer.dmg, release/${{ env.version }}/HSMod-Windows-${{ env.version }}-Setup.exe
